language: r
cache: packages

r:
  - release
  - devel

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - netcdf-bin
      - libnetcdf-dev

r_github_packages:
  - tidyverse/ggplot2
  - dgrtwo/gganimate

after_success:
  - Rscript -e 'covr::codecov()'

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""
